//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POE1Tools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealLow1 {
            get {
                return ((bool)(this["chkAutoHealLow1"]));
            }
            set {
                this["chkAutoHealLow1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealLow2 {
            get {
                return ((bool)(this["chkAutoHealLow2"]));
            }
            set {
                this["chkAutoHealLow2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealLow3 {
            get {
                return ((bool)(this["chkAutoHealLow3"]));
            }
            set {
                this["chkAutoHealLow3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealLow4 {
            get {
                return ((bool)(this["chkAutoHealLow4"]));
            }
            set {
                this["chkAutoHealLow4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealLow5 {
            get {
                return ((bool)(this["chkAutoHealLow5"]));
            }
            set {
                this["chkAutoHealLow5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealHigh1 {
            get {
                return ((bool)(this["chkAutoHealHigh1"]));
            }
            set {
                this["chkAutoHealHigh1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealHigh2 {
            get {
                return ((bool)(this["chkAutoHealHigh2"]));
            }
            set {
                this["chkAutoHealHigh2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealHigh3 {
            get {
                return ((bool)(this["chkAutoHealHigh3"]));
            }
            set {
                this["chkAutoHealHigh3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealHigh4 {
            get {
                return ((bool)(this["chkAutoHealHigh4"]));
            }
            set {
                this["chkAutoHealHigh4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoHealHigh5 {
            get {
                return ((bool)(this["chkAutoHealHigh5"]));
            }
            set {
                this["chkAutoHealHigh5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoMana1 {
            get {
                return ((bool)(this["chkAutoMana1"]));
            }
            set {
                this["chkAutoMana1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoMana2 {
            get {
                return ((bool)(this["chkAutoMana2"]));
            }
            set {
                this["chkAutoMana2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoMana3 {
            get {
                return ((bool)(this["chkAutoMana3"]));
            }
            set {
                this["chkAutoMana3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoMana4 {
            get {
                return ((bool)(this["chkAutoMana4"]));
            }
            set {
                this["chkAutoMana4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoMana5 {
            get {
                return ((bool)(this["chkAutoMana5"]));
            }
            set {
                this["chkAutoMana5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLatency1 {
            get {
                return ((bool)(this["chkFlaskLatency1"]));
            }
            set {
                this["chkFlaskLatency1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLatency2 {
            get {
                return ((bool)(this["chkFlaskLatency2"]));
            }
            set {
                this["chkFlaskLatency2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLatency3 {
            get {
                return ((bool)(this["chkFlaskLatency3"]));
            }
            set {
                this["chkFlaskLatency3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLatency4 {
            get {
                return ((bool)(this["chkFlaskLatency4"]));
            }
            set {
                this["chkFlaskLatency4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkFlaskLatency5 {
            get {
                return ((bool)(this["chkFlaskLatency5"]));
            }
            set {
                this["chkFlaskLatency5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtFlaskLatency1 {
            get {
                return ((string)(this["txtFlaskLatency1"]));
            }
            set {
                this["txtFlaskLatency1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtFlaskLatency2 {
            get {
                return ((string)(this["txtFlaskLatency2"]));
            }
            set {
                this["txtFlaskLatency2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtFlaskLatency3 {
            get {
                return ((string)(this["txtFlaskLatency3"]));
            }
            set {
                this["txtFlaskLatency3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtFlaskLatency4 {
            get {
                return ((string)(this["txtFlaskLatency4"]));
            }
            set {
                this["txtFlaskLatency4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtFlaskLatency5 {
            get {
                return ((string)(this["txtFlaskLatency5"]));
            }
            set {
                this["txtFlaskLatency5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife1 {
            get {
                return ((bool)(this["chkSkillLowLife1"]));
            }
            set {
                this["chkSkillLowLife1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife2 {
            get {
                return ((bool)(this["chkSkillLowLife2"]));
            }
            set {
                this["chkSkillLowLife2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife3 {
            get {
                return ((bool)(this["chkSkillLowLife3"]));
            }
            set {
                this["chkSkillLowLife3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLowLife4 {
            get {
                return ((bool)(this["chkSkillLowLife4"]));
            }
            set {
                this["chkSkillLowLife4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLatency1 {
            get {
                return ((bool)(this["chkSkillLatency1"]));
            }
            set {
                this["chkSkillLatency1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLatency2 {
            get {
                return ((bool)(this["chkSkillLatency2"]));
            }
            set {
                this["chkSkillLatency2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLatency3 {
            get {
                return ((bool)(this["chkSkillLatency3"]));
            }
            set {
                this["chkSkillLatency3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillLatency4 {
            get {
                return ((bool)(this["chkSkillLatency4"]));
            }
            set {
                this["chkSkillLatency4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown1 {
            get {
                return ((string)(this["txtSkillCooldown1"]));
            }
            set {
                this["txtSkillCooldown1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown2 {
            get {
                return ((string)(this["txtSkillCooldown2"]));
            }
            set {
                this["txtSkillCooldown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown3 {
            get {
                return ((string)(this["txtSkillCooldown3"]));
            }
            set {
                this["txtSkillCooldown3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public string txtSkillCooldown4 {
            get {
                return ((string)(this["txtSkillCooldown4"]));
            }
            set {
                this["txtSkillCooldown4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkDrawDebug {
            get {
                return ((bool)(this["chkDrawDebug"]));
            }
            set {
                this["chkDrawDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife1 {
            get {
                return ((bool)(this["chkSkillHighLife1"]));
            }
            set {
                this["chkSkillHighLife1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife2 {
            get {
                return ((bool)(this["chkSkillHighLife2"]));
            }
            set {
                this["chkSkillHighLife2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife3 {
            get {
                return ((bool)(this["chkSkillHighLife3"]));
            }
            set {
                this["chkSkillHighLife3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkSkillHighLife4 {
            get {
                return ((bool)(this["chkSkillHighLife4"]));
            }
            set {
                this["chkSkillHighLife4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int trkUpdateRate {
            get {
                return ((int)(this["trkUpdateRate"]));
            }
            set {
                this["trkUpdateRate"] = value;
            }
        }
    }
}
